### ISSUE TITLE
https://reddit2kindle.com --- Website doesn't seem to be working

### ISSUE THREAD

**Issue by todsandberg** [JamieMagee/reddit2kindle#33]
Hi Jamie, 

I had used your web app in the past to convert one or more articles successfully, but I checked it out today and I am not able to get it to work. I get an error message
I tried both methods available on the website (post or site) and they both say "Something Happened - Please try reloading the page"

What I tried to solve it:
I double-checked the kindle email and also made sure that my kindle settings allow for email sent from reddit2kindle.
I also tried deleting all Cookies.

Would you mind taking a look at it?
Is the web app working on your end?

Thank you.

**Comment by JamieMagee** [comment]
Thanks for reaching out. I've not used reddit2kindle myself since around 2017, and a lot of the external APIs that I've relied on have changed or disappeared entirely. Also, the recent [KindleDrip](https://medium.com/realmodelabs/kindledrip-from-your-kindles-email-address-to-using-your-credit-card-bb93dbfb2a08) attack made it very difficult to send documents to kindles.

At this stage, fixing it would mean a major rewrite. I'd like to continue supporting it, but I am lacking in available time right now.

**Comment by sw33rupi** [comment]
Hi Jamie,

thanks for your great work. Since  it is so difficult to send the documents directly to the kindle, would it be easier to send the generated file to any email-address or make it downloadable?

**Comment by pravinvibhute** [comment]
Hi,
I am an avid reader of Reddit post and relied completely on this service. Since the last few days, it is not working. I have downloaded the package, installed the Python thing and tried to run it locally on my PC. It is now running at http://127.0.0.1:5000/
**But still the same error.** 
I don't know anything about any programming language or anything still I tried to do it by learning here and there. 
I asked this question on more than 3 sub/r but no one is that helpful.
![Screenshot (3)](https://user-images.githubusercontent.com/46518871/113484233-cedca680-94c4-11eb-80a3-e3c54c090851.png)
Please do something. At least, tell how to solve this error.
Please spare your time. Thank you.

**Comment by jayantraizada** [comment]
Hey @JamieMagee,

I have made some changes to the code and created a pull request. This script is working fine for me but it requires some attention on the mercury token section.

Ciao

**Comment by JamieMagee** [comment]
Hi everyone, I'm aware of the issues with the webapp. I've started a rewrite of reddit2kindle in C#, as the current version has accumulated a lot of technical debt, and has effectively been unmaintained for a long time.

@jayantraizada Thanks for looking into it, and thanks for the PR. I'm not sure I want to merge it though, as I've also got a C# alternative. The current app doesn't deal with confirmation emails (due to [KindleDrip](https://portswigger.net/daily-swig/kindledrip-critical-vulnerabilities-in-amazon-kindle-e-reader-gave-attackers-free-rein-over-user-accounts)), whereas the rewrite does.

**Comment by JamieMagee** [comment]
I've release an MVP of the rewrite. Please check it out and open any issues for any bugs or errors you see.

As for KindleDrip, the most reliable workaround I've found is to make sure that your send-to-kindle address does no contain any part of the email address used to sign into Amazon.

**Comment by todsandberg** [comment]
Jamie, Thank you very much for getting the rewrite up! This is huge!
I loaded up my kindle and I am looking forward to reading (in the dark) on a Kindle screen instead of a phone's bright screen.

You and your work are greatly appreciated!
